baseurl = "https://chikuang.github.io/"
publishDir = "../chikuang.github.io"
languageCode = "en-us"
title = "Chi-Kuang Yeh"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout = 3000

[params]
  subtitle= "PhD Candidate"
  interests="Panel Data, Functional Data Analysis, Time Series & Experimental Design"
  cv_name= "Chi-Kuang_CV_APR_20.pdf"
  blog="https://uwaterloo.ca/scholar/c26yeh/home"

[[params.affilation]]
  name = "University of Waterloo"
  position = "PhD Candidate"
  contact = "chi-kuang.yeh@uwaterloo.ca"

#[[params.affilation]]
#  name = "MyCoolStartup"
#  position = "Co-Founder"
#  contact = "hadi@mycoolstartup.ai"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/chikuang"

[[params.social]]
  name = "Researchgate"
  icon = "researchgate"
  url = "https://www.researchgate.net/profile/Chi_Kuang_Yeh"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/chi-kuang-yeh-040523110/"


[[params.introduction.paragraph]]
  text="""Hello, thanks for stepping by! :) I am a PhD student at the [University of Waterloo](https://uwaterloo.ca) 
  under the joint supervision of Prof. [Greg Rice](https://uwaterloo.ca/statistics-and-actuarial-science/about/people/grice) 
  and Prof. [Joel Dubin](https://uwaterloo.ca/statistics-and-actuarial-science/people-profiles/joel-dubin). 
  Currently, I also work with Prof. [Martin Lysy](https://uwaterloo.ca/statistics-and-actuarial-science/people-profiles/martin-lysy) 
  and Dr. [Joslin Goh](https://uwaterloo.ca/statistics-and-actuarial-science/about/people/jtcgoh)
  at the [Statistical Consulting and Collaborative Research Unit (SCCRU)](https://uwaterloo.ca/statistical-consulting-and-collaborative-research-unit/). 
  My other personal website hosted by UWaterloo server can be found 
  [here](https://uwaterloo.ca/scholar/c26yeh/home)."""
  
[[params.introduction.paragraph]]
  text=""" Before coming to Waterloo, I obtained MSc and BSc degrees at the 
  [University of Victoria](https://www.uvic.ca/), 
  both were supervised by Prof. [Julie Zhou](https://www.uvic.ca/science/math-statistics/people/home/faculty/zhou_julie.php) 
  in a beautiful city, [Victoria](https://www.victoria.ca/), British Columbia, Canada.
  """
  
[[params.introduction.paragraph]]
  text="""In my spare time, I like to play basketball, and reading books, 
  articles and random posts.
  """
  
[[params.projects]]
	[[params.projects.project]]
		name = "Bayesian capture-recapture with tag-failure"
		description  = """This is an ongoing joint work with Dr. [Laura Cowen](https://www.uvic.ca/science/math-statistics/people/home/faculty/cowen_laura.php) 
		on investigating the under-estimated survival rate with the objects that may potentially lost tracked under the bayesian paradigm."""
		project_page = ""
		code_link = ""
		blog_link = ""

#[[params.projects]]
#	[[params.projects.project]]
#		name = "Bayesian capture-recapture with tag-failure"
#		description  = """This is an ongoing joint work with Dr. [Laura Cowen](https://www.uvic.ca/science/math-statistics/people/home/faculty/cowen_laura.php) 
#		on investigating the under-estimated survival rate with the objects that may potentially lost tracked under the bayesian paradigm."""
#		project_page = ""
#		code_link = ""
#		blog_link = ""
		
# [[params.projects.project]]
#		name = "Backtesting in real-time probabilistic forecasts"
#		description  = ""
#		project_page = "../post/chi-kuang_projects.html"
#		code_link = ""
#		blog_link = ""

# [[params.projects.project]]
#		name = "Integer eget aliquet nibh praesent tristique magna"
#		description  = ""
#		project_page = "https://myprojecthomepage.com"
#		code_link = ""
#		blog_link = "https://ablogpost.com"

#[[params.publications]]
#  year="Preprint"

#  [[params.publications.paper]]
#    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
#    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
#    dest  = "Helga Zita Journal"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#    name = "In cursus turpis massa tincidunt dui ut ornare lectus sit"
#    authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
#    dest  = "Meklit Katlego Conference"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"

[[params.publications]]
  year = "2019"

  [[params.publications.paper]]
		name = "Properties of optimal regression designs under the second-order least squares estimator"
		authors = "**Chi-Kuang Yeh** & Julie Zhou"
		dest  = "Statistical Papers"
		link = "https://link.springer.com/article/10.1007%2Fs00362-018-01076-6"
		code_link = ""
		blog_link = ""

#  [[params.publications.paper]]
#		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
#		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
#		dest  = "Zorka Vita Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
#		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
#		dest  = "Lena Randa Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = ""

#  [[params.publications.paper]]
#		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
#		authors = "__Hadi Sinaee__, Caroll Comes"
#		dest  = "Thandeka Radhika Conference"
#		link = ""
#		code_link = ""
#		blog_link = ""
