baseURL: https://graciadong.github.io
publishDir: "../graciadong.github.io"
languageCode: en-us
title: Gracia Yunruo Dong
theme: hugo-theme-notrack
newContentEditor: nvim
mainSections: blog
paginate: 4
params:
  author: Gracia Yunruo Dong
  blogLatestHeading: My writing
  favicon: GYD_icon.png
  mainSections: blog
  nBlogLatest: 4
  showBlogLatest: no
  showTaxonomyLinks: no
  siteHeading: Gracia Yunruo Dong, PhD
  social:
    email: gracia.dong@utoronto.ca
    linkedin: graciadong
    googlescholar: zWbZMVsAAAAJ
    orcid: 0000-0003-0026-4009
    twitter: DongGracia
taxonomies:
  categories: categories
  month: month
  tags: tags
  year: year
permalinks:
  blog: /blog/:year/:month/:slug
