baseurl = "https://chikuang.github.io/"
publishDir = "../chikuang.github.io"
languageCode = "en-us"
title = "Chi-Kuang Yeh"
theme = "avicenna"
googleAnalytics = "UA-1234-6"
timeout = 3000

[params]
  subtitle= "PhD Candidate"
  interests = """I am interested in a lot of areas, but for now, my research 
  is centred around Functional data analysis, espeically with dependence, 
      time series analysis
    & optimal design of experimental"""
  cv_name= "CV_YCK_Sep20_2022.pdf"
  blog="https://uwaterloo.ca/scholar/c26yeh/home"

[[params.affilation]]
  name = "University of Waterloo"
  position = "PhD(c) in Statistics"
  contact = "chi-kuang.yeh@uwaterloo.ca"

[[params.social]]
  name = "GitHub"
  icon = "github"
  url = "https://github.com/chikuang"
  
[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/chi-kuang-yeh-040523110/"

[[params.social]]
  name = "Researchgate"
  icon = "book-open"
  url = "https://www.researchgate.net/profile/Chi_Kuang_Yeh"

[[params.introduction.paragraph]]
  text = """**Note**: I am currently the co-organizer of the departmental 
  [student seminar series](https://uwaterloo.ca/statistics-and-actuarial-science/events/student-seminar-series)
  along with [Minzee Kim](https://www.linkedin.com/in/minzee-kim-14555a130/?originalSubdomain=ca)."""


[[params.introduction.paragraph]]
  text = """**About me**: I am a final year PhD student at the 
  [University of Waterloo](https://uwaterloo.ca) working with Profs. 
  [Gregory Rice](https://uwaterloo.ca/statistics-and-actuarial-science/about/people/grice) and 
  [Joel A. Dubin](https://uwaterloo.ca/statistics-and-actuarial-science/people-profiles/joel-dubin).
  Previously, I received BSc and MSc degrees from the [University of Victoria](https://www.uvic.ca/) under 
  the supervision of Prof. [Julie Zhou](https://www.uvic.ca/science/math-statistics/people/home/faculty/zhou_julie.php). 
  I also work closely with Prof. [Peijun Sang](https://uwaterloo.ca/scholar/psang)."""

#[[params.projects]] 
#[[params.projects.project]]
#	name = "Statistical inference on functonal times series"
#	description  = """Ongoing joint work with my supervisors:
#	    Prof. Gregory Rice and Prof. Joel A. Dubin."""
#	project_page = ""
#	code_link = ""
#	blog_link = ""

#[[params.projects.project]]
#  name = "Capture-recapture modeling in Bayesian paradigm"
#	description  = """Ongoing joint work with Prof. 
#	[Laura L.E. Cowen](https://www.uvic.ca/science/math-statistics/people/home/faculty/cowen_laura.php) 
#	 at the University of Victoria."""
#	project_page = ""
#	code_link = ""
#	blog_link = ""

[[params.publications]]
year = "Preprint"

[[params.publications.paper]]
name = """Functional Spherical Autocorrelation: A Robust Estimate 
  of the Autocorrelation of a Functional Time Series"""
 authors  = "**Chi-Kuang Yeh**, Gregory Rice & Joel A. Dubin"
 dest  = "arXiv:2207.05806"
 link = "https://arxiv.org/abs/2207.05806"
 code_link = ""
 blog_link = ""

[[params.publications]]
year = "2022"
[[params.publications.paper]]
name = """Evaluating real-time probabilistic forecasts with application to 
 	  National Basketball Association outcome prediction"""
 authors  = "**Chi-Kuang Yeh**, Gregory Rice & Joel A. Dubin"
 dest  = "The American Statistician, 76, 214--223"
 link = "https://www.tandfonline.com/doi/abs/10.1080/00031305.2021.1967781?journalCode=utas20"
 code_link = "https://github.com/chikuang/evalRTPF"
 blog_link = ""

[[params.publications]]
year = "2021"
[[params.publications.paper]]
name = "Properties of optimal regression designs under the second-order least squares estimator"
authors = "**Chi-Kuang Yeh** & Julie Zhou"
dest  = "Statistical Papers, 62, 75--92"
link = "https://link.springer.com/article/10.1007%2Fs00362-018-01076-6"
code_link = "https://github.com/chikuang/OptimalDesigns-SLSE"
log_link = ""
	
[[params.publications]]
  year="Thesis"
[[params.publications.paper]]
	name = "Optimal regression design under second-order least squares estimator: theory, algorithm and applications"
	authors = "**Chi-Kuang Yeh**"
	dest  = "Master's Thesis, University of Victoria"
	link = "https://dspace.library.uvic.ca/handle/1828/9765"
	code_link = ""
	blog_link = ""

# [[params.projects.project]]
#		name = "Integer eget aliquet nibh praesent tristique magna"
#		description  = ""
#		project_page = "https://myprojecthomepage.com"
#		code_link = ""
#		blog_link = "https://ablogpost.com"

#[[params.publications]]
#  year="Preprint"

#  [[params.publications.paper]]
#    name = "Enim nunc faucibus a pellentesque sit amet porttitor"
#    authors = "Ana Alvardo, William Worthley, __Hadi Sinaee__"
#    dest  = "Helga Zita Journal"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#    name = "In cursus turpis massa tincidunt dui ut ornare lectus sit"
#    authors = "__Hadi Sinaee__,Les Larkins, Edra Ethier"
#    dest  = "Meklit Katlego Conference"
#    link = "https://mypaperishere.com"
#    code_link = "https://thecoderepo.com"
#    blog_link = "https://myblogaboutit.com"



#  [[params.publications.paper]]
#		name = "Venenatis urna cursus eget nunc. Nam aliquam sem et tortor consequat id porta nibh venenatis"
#		authors = "Les Larkins, Ana Alvardo, __Hadi Sinaee__ "
#		dest  = "Zorka Vita Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = "https://myblogaboutit.com"

#  [[params.publications.paper]]
#		name = "Aliquet eget sit amet tellus cras adipiscing enim eu turpis"
#		authors = "Les Larkins, __Hadi Sinaee__, Ana Alvardo"
#		dest  = "Lena Randa Conference"
#		link = "https://mypaperishere.com"
#		code_link = ""
#		blog_link = ""

#  [[params.publications.paper]]
#		name = "Orci eu lobortis elementum nibh tellus molestie nunc non blandit"
#		authors = "__Hadi Sinaee__, Caroll Comes"
#		dest  = "Thandeka Radhika Conference"
#		link = ""
#		code_link = ""
#		blog_link = ""
